=== md1961/holy-xml/holiday_rules.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:element name="holidays"            type="listHolidays" />
  <xsd:element name="holiday"             type="holidayType" />
  <xsd:element name="is_substitutable"    type="xsd:boolean" />

  <xsd:element name="fixed_rule"          type="fixedHolidayRuleType" /> 
  <xsd:element name="semi_fixed_rule"     type="semiFixedHolidayRuleType" /> 
  <xsd:element name="day_formulated_rule" type="dayFormulatedHolidayRuleType" /> 
  <xsd:element name="conditional_rule"    type="conditionalHolidayRuleType" /> 

  <xsd:element name="year_from"           type="yearType" /> 
  <xsd:element name="year_to"             type="yearType" /> 
  <xsd:element name="month"               type="monthType" /> 
  <xsd:element name="day"                 type="dayType" /> 
  <xsd:element name="week_number"         type="weekNumberType" /> 
  <xsd:element name="day_of_week"         type="dayOfWeekType" /> 
  <xsd:element name="day_formula"         type="formulaType" />
  <xsd:element name="condition"           type="formulaType" />

  <xsd:attribute name="name"              type="xsd:string" />
  <xsd:attribute name="english_name"      type="xsd:string" />
  <xsd:attribute name="language"          type="languageType" />

  <xsd:complexType name="listHolidays">
    <xsd:sequence>
      <xsd:element ref="holiday" maxOccurs="unbounded" /> 
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="holidayType">
    <xsd:sequence>
      <xsd:element ref="is_substitutable" /> 
      <xsd:choice minOccurs="0" maxOccurs="unbounded"> 
        <xsd:element ref="fixed_rule" />
        <xsd:element ref="semi_fixed_rule" />
        <xsd:element ref="day_formulated_rule" />
        <xsd:element ref="conditional_rule" />
      </xsd:choice>
    </xsd:sequence>
    <xsd:attribute ref="name" /> 
    <xsd:attribute ref="english_name" /> 
  </xsd:complexType>

  <xsd:complexType name="baseHolidayRuleType">
    <xsd:sequence>
      <xsd:element ref="year_from" /> 
      <xsd:element ref="year_to" /> 
      <xsd:element ref="month" /> 
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="fixedHolidayRuleType">
    <xsd:complexContent>
      <xsd:extension base="baseHolidayRuleType">
        <xsd:sequence>
          <xsd:element ref="day" />
        </xsd:sequence>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>

  <xsd:complexType name="semiFixedHolidayRuleType">
    <xsd:complexContent>
      <xsd:extension base="baseHolidayRuleType">
        <xsd:sequence>
          <xsd:element ref="week_number" />
          <xsd:element ref="day_of_week" />
        </xsd:sequence>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>

  <xsd:complexType name="dayFormulatedHolidayRuleType">
    <xsd:complexContent>
      <xsd:extension base="baseHolidayRuleType">
        <xsd:sequence>
          <xsd:element ref="day_formula" />
        </xsd:sequence>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>

  <xsd:complexType name="conditionalHolidayRuleType">
    <xsd:complexContent>
      <xsd:extension base="baseHolidayRuleType">
        <xsd:sequence>
          <xsd:element ref="condition" />
        </xsd:sequence>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>

  <xsd:simpleType name="yearType">
    <xsd:restriction base="xsd:string">
      <xsd:pattern value="\d{4}|unbounded" />
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name="monthType">
    <xsd:restriction base="xsd:string">
      <xsd:pattern value="[1-9]|1[012]|any" />
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name="dayType">
    <xsd:restriction base="xsd:string">
      <xsd:pattern value="[1-9]|[12]\d|3[01]" />
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name="weekNumberType">
    <xsd:restriction base="xsd:string">
      <xsd:pattern value="[1-5]" />
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name="dayOfWeekType">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="Monday"    />
      <xsd:enumeration value="Tuesday"   />
      <xsd:enumeration value="Wednesday" />
      <xsd:enumeration value="Thursday"  />
      <xsd:enumeration value="Friday"    />
      <xsd:enumeration value="Saturday"  />
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:complexType name="formulaType">
    <xsd:simpleContent>
      <xsd:extension base="xsd:string">
        <xsd:attribute ref="language" use="required" />
      </xsd:extension>
    </xsd:simpleContent>
  </xsd:complexType>

  <xsd:simpleType name="languageType">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="Ruby" />
    </xsd:restriction>
  </xsd:simpleType>
</xsd:schema>

=== md1961/holy-xml/holiday_rules.xml
<holidays
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="holiday_rules.xsd"
    >

  <holiday name="元日" english_name="New Year's Day">
    <is_substitutable>true</is_substitutable>
    <fixed_rule>
      <year_from>1949</year_from>
      <year_to>unbounded</year_to>
      <month>1</month>
      <day>1</day>
    </fixed_rule>
  </holiday>

  <holiday name="海の日" english_name="Marine Day">
    <is_substitutable>false</is_substitutable>
    <semi_fixed_rule>
      <year_from>2003</year_from>
      <year_to>unbounded</year_to>
      <month>7</month>
      <week_number>3</week_number>
      <day_of_week>Monday</day_of_week>
    </semi_fixed_rule>
  </holiday>

  <holiday name="春分の日" english_name="Vernal Equinox Day">
    <is_substitutable>true</is_substitutable>
    <day_formulated_rule>
      <year_from>1851</year_from>
      <year_to>1899</year_to>
      <month>3</month>
      <day_formula language="Ruby">
        <![CDATA[
          (19.8277 + 0.242194 * (year - 1980) - ((year - 1983) / 4).floor)).floor
        ]]>
      </day_formula>
    </day_formulated_rule>
  </holiday>

  <holiday name="国民の祝日" english_name="Citizen's Holiday">
    <is_substitutable>false</is_substitutable>
    <conditional_rule>
      <year_from>2003</year_from>
      <year_to>unbounded</year_to>
      <month>any</month>
      <condition language="Ruby">
        <![CDATA[
          holiday?(prev_day) && substitutable?(prev_day) && holiday?(next_day) && substitutable?(next_day)
        ]]>
      </condition>
    </conditional_rule>
  </holiday>
</holidays>
